### ISSUE TITLE
Official version release time?

### ISSUE THREAD

**Issue by g0tbread** [microconfig/microconfig-server#3]
Hi,@kapodes
The tool is pretty good, when will the stable version be released?
Thanks.

**Comment by kapodes** [comment]
@g0tbread hello and thanks for your interested. It's currently in pretty stable and working state. Are you already using microconfig-server?

**Comment by g0tbread** [comment]
> @g0tbread hello and thanks for your interested. It's currently in pretty stable and working state. Are you already using microconfig-server?

Not yet，ha
But, I've tried using microconfig and read the relevant documents. It is indeed a very useful tool. I look forward to the early release of the stable version of microconfig-server.
Thanks.

**Comment by kapodes** [comment]
> > @g0tbread hello and thanks for your interested. It's currently in pretty stable and working state. Are you already using microconfig-server?
> 
> Not yet，ha But, I've tried using microconfig and read the relevant documents. It is indeed a very useful tool. I look forward to the early release of the stable version of microconfig-server. Thanks.

It's already pretty stable and is used in prod environment for couple years already. Please try it out and see if it works for you :)
